import type { SceneYearAnalysis, LocalEngineInput } from "./hydrologicalEngine.js";
import type { ScoredChunk } from "./retriever.js";

export interface SynthesisInput {
  waterBody?: string;
  bbox: [number, number, number, number];
  years: string[];
  perYear: SceneYearAnalysis[];
  areaStats: any;
  retrievedChunks: ScoredChunk[];
}

function fmt(n: number, d = 2): string {
  return Number.isFinite(n) ? n.toFixed(d) : "0.00";
}

/**
 * Local specialized hydrological synthesizer. Compiles retrieved RAG
 * knowledge + 12-D feature embeddings + few-shot classification into a
 * structured, dependency-free environmental assessment. Runs entirely
 * in-process with deterministic latency (no cloud LLM call).
 */
export function synthesizeAssessment(input: SynthesisInput): string {
  const name = (input.waterBody || "Target Basin").replace(/_/g, " ");
  const baseline = input.perYear[0];
  const latest = input.perYear[input.perYear.length - 1];

  const waterBase = baseline?.classification.classes.water?.km2 ?? 0;
  const waterLat = latest?.classification.classes.water?.km2 ?? 0;
  const waterChange = waterLat - waterBase;
  const waterPct = waterBase ? (waterChange / waterBase) * 100 : 0;

  const wqi = latest?.indices?.["WQI"] ?? 0;
  const ndti = latest?.indices?.["NDTI"] ?? 0;
  const ndci = latest?.indices?.["NDCI"] ?? 0;
  const ndwi = latest?.indices?.["NDWI"] ?? 0;

  const dominant = latest?.classification.dominant ?? "water";
  const latestYear = latest?.year ?? (input.years[input.years.length - 1] || "T1");
  const baseYear = baseline?.year ?? (input.years[0] || "T0");

  const wqiBand =
    wqi >= 70 ? "good" : wqi >= 45 ? "moderate" : wqi >= 25 ? "poor" : "critical";
  const turbidityBand =
    ndti > 0.1 ? "high sediment load" : ndti > 0.03 ? "moderate sediment" : "low turbidity";
  const bloomBand = ndci > 0.2 ? "active algal bloom risk" : "low chlorophyll";

  const lines: string[] = [];
  lines.push(`# Local Hydrological Assessment — ${name}`);
  lines.push("");
  lines.push(
    `**Multi-Sensor 12-D Signature (${latestYear}):** NDWI ${fmt(ndwi)} · MNDWI ${fmt(
      latest?.indices?.["MNDWI"] ?? 0
    )} · NDTI ${fmt(ndti)} · NDCI ${fmt(ndci)} · SAR σ⁰ VV ${fmt(
      latest?.indices?.["VV"] ?? 0
    )} dB · ΔDEM ${fmt(latest?.indices?.["ΔDEM"] ?? 0, 1)} m · WQI ${fmt(wqi, 0)}/100 (${wqiBand}).`
  );
  lines.push("");
  lines.push("## 1. Land-Cover Classification (Few-Shot, Logistic Regression)");
  const cls = latest?.classification.classes ?? {};
  for (const c of ["water", "wetland", "built_up"]) {
    const frac = ((cls[c]?.fraction ?? 0) * 100).toFixed(1);
    const km2 = (cls[c]?.km2 ?? 0).toFixed(2);
    lines.push(`- **${c}**: ${frac}% (${km2} km²)`);
  }
  lines.push(`- Dominant class: **${dominant}**.`);
  lines.push("");
  lines.push("## 2. Surface Water Trajectory");
  const dir = waterChange >= 0 ? "gained" : "lost";
  lines.push(
    `- Baseline (${baseYear}): ${fmt(waterBase)} km² → Target (${latestYear}): ${fmt(
      waterLat
    )} km².`
  );
  lines.push(
    `- Net water ${dir}: **${waterChange >= 0 ? "+" : ""}${fmt(waterChange)} km² (${fmt(
      waterPct
    )}%)**.`
  );
  lines.push(
    `- Bio-optical state: ${turbidityBand}, ${bloomBand}, composite WQI ${fmt(wqi, 0)}/100.`
  );
  lines.push("");
  lines.push("## 3. Statutory & Scientific Guidance (RAG Retrieval)");
  for (const chunk of input.retrievedChunks.slice(0, 4)) {
    lines.push(
      `- [${chunk.source}](${chunk.category}) — ${chunk.text} _(relevance ${fmt(
        chunk.score,
        2
      )})_`
    );
  }
  lines.push("");
  lines.push("## 4. Actionable Interventions");
  const interventions: string[] = [];
  if (waterPct < -5) {
    interventions.push(
      "Prioritize desilting and recharge corridors; enforce a radar-verified eco-perimeter to arrest water loss."
    );
  } else if (waterPct > 5) {
    interventions.push(
      "Strengthen flood-buffer vegetation and monitor encroachment as monsoon inundation expands surface water."
    );
  } else {
    interventions.push(
      "Maintain status-quo monitoring; track interannual NDWI and WQI for early degradation signals."
    );
  }
  if (wqi < 45) {
    interventions.push(
      "Address eutrophication and turbidity via nutrient-runoff controls and sedimentation management to lift WQI."
    );
  }
  if (ndci > 0.2) {
    interventions.push(
      "Deploy algal-bloom mitigation (aeration, macrophyte management) given elevated chlorophyll-a (NDCI)."
    );
  }
  interventions.push(
    "Align conservation actions with Ramsar ecological-character obligations and CPCB water-quality class targets."
  );
  for (const iv of interventions) lines.push(`- ${iv}`);
  lines.push("");
  lines.push(
    `_Generated by the in-process Local Hydrological RAG engine (spectral_12d encoder + few-shot classifier + TF-IDF retriever). No external cloud dependency._`
  );

  return lines.join("\n");
}
